filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
   
setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "password"
 
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]